packages: []
minimumReleaseAge: 4320
allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - app-builder-lib@26.15.3
  - builder-util@26.15.3
  - dmg-builder@26.15.3
  - electron-builder-squirrel-windows@26.15.3
  - electron-builder@26.15.3
  - electron-publish@26.15.3
  - esbuild@0.28.2
  - "@esbuild/*"
  - baseline-browser-mapping@2.11.13
  - browserslist@4.28.8
  - electron-to-chromium@1.5.403

overrides:
  node-abi: ^4.33.0
