[package]
name = "media-ctrl"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.1", features = ["tokio_rt", "napi9"] }
napi-derive = "3.6.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "local-time",
] }
tracing-appender = "0.2"
time = { version = "0.3", features = ["macros", "formatting"] }

# Discord RPC
discord-rich-presence = "1.0"
url = "2.5"

[build-dependencies]
napi-build = "2.4.1"

# Windows
[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.62"
features = ["Media_Playback", "Storage_Streams", "Win32_System_Com"]

# Linux
[target.'cfg(target_os = "linux")'.dependencies]
mpris-server = "0.9"
tempfile = "3.24"

# macOS
[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
objc2-media-player = "0.3"

[lints]
workspace = true
